# 00. PyTorch fundamentals

In [2]:
import torch

In [6]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [10]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [9]:
x_reshaped_2 = x.reshape(1,9)
x_reshaped_2

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

### view
* a view shares the memory with the original tensor
* transpose x.T also has the same memory as x

In [12]:
z = x.view(3,3)
z, x

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [21]:
x_stacked = torch.stack([x,x,x], dim = 1)
x_stacked, x_stacked.shape

(tensor([[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.],
         [8., 8., 8.],
         [9., 9., 9.]]),
 torch.Size([9, 3]))

In [23]:
x_vstacked = torch.vstack([x,x,x])
x_vstacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [18]:
x_hstacked = torch.hstack([x,x,x])
x_hstacked

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.,
        1., 2., 3., 4., 5., 6., 7., 8., 9.])

### squeeze()
* removes all single dimension

In [26]:
x_squeezed = x_reshaped_2.squeeze()
print(f"x_squeezed = {x_squeezed}")
print(f"x_squeezed.shape = {x_squeezed.shape}")

x_squeezed = tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
x_squeezed.shape = torch.Size([9])


### unsqueeze(dim=n) 
* adds single dimension at specified dimension


In [28]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"x_unsqueezed = {x_unsqueezed}")
print(f"x_unsqueezed.shape = {x_unsqueezed.shape}")

x_unsqueezed = tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
x_unsqueezed.shape = torch.Size([9, 1])


### permute()
* rearranges the dimensions of tensor in specified order
* so changes the order of co-ordinates of the points present -- for understanding purposes
* shares the same memory with the tensor, just a different view

In [11]:
f = torch.rand(5,4,3)
f

tensor([[[7.6667e-01, 6.9855e-01, 8.5782e-01],
         [9.4363e-01, 1.9238e-01, 9.3906e-01],
         [7.5315e-01, 8.2875e-01, 7.6052e-01],
         [4.3362e-01, 3.7557e-01, 7.1434e-01]],

        [[5.8051e-01, 6.1429e-01, 7.2896e-01],
         [6.5439e-01, 6.8005e-01, 6.7555e-01],
         [3.2886e-01, 9.7527e-03, 8.4916e-01],
         [8.1976e-01, 3.4605e-01, 2.5784e-01]],

        [[3.8553e-01, 7.8224e-01, 2.1341e-01],
         [3.2773e-02, 9.0066e-01, 6.4390e-01],
         [6.8509e-01, 4.8316e-01, 9.7974e-01],
         [4.8397e-01, 3.4309e-01, 2.1262e-01]],

        [[9.4476e-01, 5.8448e-01, 9.7278e-01],
         [6.8758e-01, 4.4112e-01, 7.8538e-01],
         [3.3728e-01, 2.2768e-01, 7.7094e-01],
         [4.1081e-01, 6.6183e-01, 9.6317e-01]],

        [[8.4820e-01, 4.0117e-01, 8.2996e-01],
         [2.9916e-01, 2.2899e-01, 3.4293e-01],
         [5.9106e-01, 6.2720e-01, 2.8559e-01],
         [8.6981e-04, 9.6865e-01, 3.0176e-01]]])

In [24]:
f_permuted = f.permute(2,0,1)
f_permuted

tensor([[[7.6667e-01, 9.4363e-01, 7.5315e-01, 4.3362e-01],
         [5.8051e-01, 6.5439e-01, 3.2886e-01, 8.1976e-01],
         [3.8553e-01, 3.2773e-02, 6.8509e-01, 4.8397e-01],
         [9.4476e-01, 6.8758e-01, 3.3728e-01, 4.1081e-01],
         [8.4820e-01, 2.9916e-01, 5.9106e-01, 8.6981e-04]],

        [[6.9855e-01, 1.9238e-01, 8.2875e-01, 3.7557e-01],
         [6.1429e-01, 6.8005e-01, 9.7527e-03, 3.4605e-01],
         [7.8224e-01, 9.0066e-01, 4.8316e-01, 3.4309e-01],
         [5.8448e-01, 4.4112e-01, 2.2768e-01, 6.6183e-01],
         [4.0117e-01, 2.2899e-01, 6.2720e-01, 9.6865e-01]],

        [[8.5782e-01, 9.3906e-01, 7.6052e-01, 7.1434e-01],
         [7.2896e-01, 6.7555e-01, 8.4916e-01, 2.5784e-01],
         [2.1341e-01, 6.4390e-01, 9.7974e-01, 2.1262e-01],
         [9.7278e-01, 7.8538e-01, 7.7094e-01, 9.6317e-01],
         [8.2996e-01, 3.4293e-01, 2.8559e-01, 3.0176e-01]]])

In [8]:
f_one = f.reshape(-1)
f_one

tensor([0.4429, 0.3686, 0.7445, 0.2271, 0.2849, 0.4194, 0.4753, 0.7068, 0.8994,
        0.3917, 0.8800, 0.0635, 0.6546, 0.0323, 0.4626, 0.7485, 0.5581, 0.1301,
        0.3156, 0.8301, 0.2092, 0.1782, 0.5028, 0.4370, 0.3829, 0.1980, 0.2908,
        0.6373, 0.2276, 0.5396, 0.3895, 0.9436, 0.8450, 0.8190, 0.8883, 0.5996,
        0.6275, 0.5741, 0.8126, 0.5102, 0.9182, 0.2417, 0.7117, 0.6189, 0.7523,
        0.8780, 0.2718, 0.1098, 0.9933, 0.0896, 0.4323, 0.9794, 0.5449, 0.1444,
        0.2127, 0.7718, 0.8559, 0.7245, 0.3147, 0.7465])

In [10]:
f_permuted_one = f_permuted.reshape(-1)
f_permuted_one

tensor([0.4429, 0.2271, 0.4753, 0.3917, 0.6546, 0.7485, 0.3156, 0.1782, 0.3829,
        0.6373, 0.3895, 0.8190, 0.6275, 0.5102, 0.7117, 0.8780, 0.9933, 0.9794,
        0.2127, 0.7245, 0.3686, 0.2849, 0.7068, 0.8800, 0.0323, 0.5581, 0.8301,
        0.5028, 0.1980, 0.2276, 0.9436, 0.8883, 0.5741, 0.9182, 0.6189, 0.2718,
        0.0896, 0.5449, 0.7718, 0.3147, 0.7445, 0.4194, 0.8994, 0.0635, 0.4626,
        0.1301, 0.2092, 0.4370, 0.2908, 0.5396, 0.8450, 0.5996, 0.8126, 0.2417,
        0.7523, 0.1098, 0.4323, 0.1444, 0.8559, 0.7465])

In [26]:
f[0,0,0] = 1
f, f_permuted

(tensor([[[1.0000e+00, 6.9855e-01, 8.5782e-01],
          [9.4363e-01, 1.9238e-01, 9.3906e-01],
          [7.5315e-01, 8.2875e-01, 7.6052e-01],
          [4.3362e-01, 3.7557e-01, 7.1434e-01]],
 
         [[5.8051e-01, 6.1429e-01, 7.2896e-01],
          [6.5439e-01, 6.8005e-01, 6.7555e-01],
          [3.2886e-01, 9.7527e-03, 8.4916e-01],
          [8.1976e-01, 3.4605e-01, 2.5784e-01]],
 
         [[3.8553e-01, 7.8224e-01, 2.1341e-01],
          [3.2773e-02, 9.0066e-01, 6.4390e-01],
          [6.8509e-01, 4.8316e-01, 9.7974e-01],
          [4.8397e-01, 3.4309e-01, 2.1262e-01]],
 
         [[9.4476e-01, 5.8448e-01, 9.7278e-01],
          [6.8758e-01, 4.4112e-01, 7.8538e-01],
          [3.3728e-01, 2.2768e-01, 7.7094e-01],
          [4.1081e-01, 6.6183e-01, 9.6317e-01]],
 
         [[8.4820e-01, 4.0117e-01, 8.2996e-01],
          [2.9916e-01, 2.2899e-01, 3.4293e-01],
          [5.9106e-01, 6.2720e-01, 2.8559e-01],
          [8.6981e-04, 9.6865e-01, 3.0176e-01]]]),
 tensor([[[1.0000e+00, 9.

### Indexing - selecting data from tensors

In [3]:
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [4]:
x[0], x[0][0], x[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

use ":" to select "all" of the target dimension

In [5]:
x[:,0]

tensor([[1, 2, 3]])

get all values from 0th and 1st dimensions but only index 1 of second dimension

In [6]:
x[:,:,1]

tensor([[2, 5, 8]])

### back and forth between numpy and torch
* torch.from_numpy()
* torch.Tensor.numpy()
* have different memory
* torch preserves the datatype of numpy as f64, which is not torch default (f32)
* going from torch to numpy preserves it as f32

In [1]:
import torch
import numpy as np

In [6]:
array = np.arange(1,8)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor


(array([1, 2, 3, 4, 5, 6, 7]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [7]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor.dtype, numpy_tensor.dtype

(torch.float32, dtype('float32'))

### Reproducibility
* **random seed**
* works per **use** basis


In [32]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
A = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
B = torch.rand(3, 4)

C = torch.rand(3, 4)

print(A == B)
print("\n")
print(A == C)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


### check for gpu access

In [34]:
torch.cuda.is_available()

True

In [35]:
torch.cuda.device_count()

1

In [36]:
!nvidia-smi


Sun Aug  2 11:53:27 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 610.43.03              KMD Version: 610.43.03     CUDA UMD Version: 13.3     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4050 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   41C    P8              1W /   60W |      27MiB /   6141MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [48]:
B = A.to('cuda')
C = B.cpu().numpy()
print(A, B, C)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]], device='cuda:0') [[0.88226926 0.91500396 0.38286376 0.95930564]
 [0.3904482  0.60089535 0.25657248 0.7936413 ]
 [0.94077146 0.13318592 0.9345981  0.59357965]]


In [46]:
B

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]], device='cuda:0')